name: Check Pull Request
on:
  pull_request:
jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache data for pnpm and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
          run_install: true

  type-check:
    runs-on: ubuntu-latest
    needs:
      - cache-and-install
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache for pnpm and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
          run_install: false

      - uses: nrwl/nx-set-shas@v2

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-type-check-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-type-check-
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - run: npx nx affected --target=type-check --base=main --head=HEAD

  lint:
    runs-on: ubuntu-latest
    needs:
      - cache-and-install
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache for pnpm and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
          run_install: false

      - uses: nrwl/nx-set-shas@v2

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-lint-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-lint-
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - run: npx nx affected --target=lint --base=main --head=HEAD

  stylelint:
    runs-on: ubuntu-latest
    needs:
      - cache-and-install
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache for pnpm and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
          run_install: false

      - uses: nrwl/nx-set-shas@v2

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-stylelint-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-stylelint-
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - run: npx nx affected --target=stylelint --base=main --head=HEAD

  test:
    runs-on: ubuntu-latest
    needs:
      - cache-and-install
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache for pnpm and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
          run_install: false

      - uses: nrwl/nx-set-shas@v2

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-test-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-test-
            cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - run: npx nx affected --target=test --base=main --head=HEAD
